// <auto-generated />
using L01_2022CI650_2022VS601.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace L01_2022CI650_2022VS601.Migrations
{
    [DbContext(typeof(RestauranteDbContext))]
    partial class RestauranteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("L01_2022CI650_2022VS601.Models.Clientes", b =>
                {
                    b.Property<int>("clienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("clienteId"));

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("clienteId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("L01_2022CI650_2022VS601.Models.Motoristas", b =>
                {
                    b.Property<int>("motoristaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("motoristaId"));

                    b.Property<string>("nombreMotorista")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("motoristaId");

                    b.ToTable("Motoristas");
                });

            modelBuilder.Entity("L01_2022CI650_2022VS601.Models.Pedidos", b =>
                {
                    b.Property<int>("pedidoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("pedidoId"));

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<int>("clienteId")
                        .HasColumnType("int");

                    b.Property<int>("motoristaId")
                        .HasColumnType("int");

                    b.Property<int>("platoId")
                        .HasColumnType("int");

                    b.Property<decimal>("precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("pedidoId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("L01_2022CI650_2022VS601.Models.Platos", b =>
                {
                    b.Property<int>("platoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("platoId"));

                    b.Property<string>("nombrePlato")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("platoId");

                    b.ToTable("Platos");
                });
#pragma warning restore 612, 618
        }
    }
}
